#!/bin/bash

# Auto-Build Environment Setup
# Project: Project Management Dashboard
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Project Management Dashboard"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# Check prerequisites
check_prerequisites() {
    echo "Checking prerequisites..."

    # Check Node.js version
    if ! command -v node &> /dev/null; then
        echo -e "${RED}Node.js is not installed${NC}"
        exit 1
    fi

    NODE_VERSION=$(node -v | cut -d'.' -f1 | sed 's/v//')
    if [ "$NODE_VERSION" -lt 20 ]; then
        echo -e "${RED}Node.js 20.9+ required (found $(node -v))${NC}"
        exit 1
    fi
    echo -e "${GREEN}Node.js $(node -v) OK${NC}"

    # Check npm
    if ! command -v npm &> /dev/null; then
        echo -e "${RED}npm is not installed${NC}"
        exit 1
    fi
    echo -e "${GREEN}npm $(npm -v) OK${NC}"

    # Check git
    if ! command -v git &> /dev/null; then
        echo -e "${RED}git is not installed${NC}"
        exit 1
    fi
    echo -e "${GREEN}git $(git --version | cut -d' ' -f3) OK${NC}"

    # Check if projects directory exists
    PROJECTS_PATH="${PROJECTS_PATH:-$HOME/Documents/Projects}"
    if [ ! -d "$PROJECTS_PATH" ]; then
        echo -e "${YELLOW}Warning: Projects directory not found at $PROJECTS_PATH${NC}"
    else
        echo -e "${GREEN}Projects directory found at $PROJECTS_PATH${NC}"
    fi
}

# ============================================
# CHECK PREREQUISITES
# ============================================
check_prerequisites

# ============================================
# INSTALL DEPENDENCIES (if not already done)
# ============================================
if [ ! -d "node_modules" ]; then
    echo ""
    echo "Installing dependencies..."
    npm install
fi

# ============================================
# START DASHBOARD
# ============================================
echo ""
echo "Starting Dashboard (Next.js 15)..."
npm run dev &
DASHBOARD_PID=$!

# Wait for dashboard to be ready
wait_for_service 3000 "Dashboard"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Dashboard: http://localhost:3000"
echo "  API:       http://localhost:3000/api/projects"
echo ""
echo "Environment:"
echo "  PROJECTS_PATH: ${PROJECTS_PATH:-$HOME/Documents/Projects}"
echo ""
echo "Process ID: $DASHBOARD_PID"
echo ""
echo "To stop: kill $DASHBOARD_PID"
echo ""
